title: "Granite Depot"
description: "Описание сайта"

# Исключение node_modules из обработки Jekyll
exclude:
  - node_modules
  - node_modules/**/*
  - styles/sass/node_modules
  - styles/sass/node_modules/**/*
